

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: elastic-operator
  labels:
    {{- include "eckupgrade.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      labels:
        control-plane: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: docker.elastic.co/eck/eck-operator:1.0.0-beta1
        name: manager
        args: ["manager", "--operator-roles", "all", "--enable-debug-logs=false"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET
            value: webhook-server-secret
          - name: WEBHOOK_PODS_LABEL
            value: elastic-operator
          - name: OPERATOR_IMAGE
            value: docker.elastic.co/eck/eck-operator:1.0.0-beta1
        resources:
          limits:
            cpu: 1
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
      terminationGracePeriodSeconds: 10

